name: CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop, new_dose_comp_csd ]

jobs:
  unit_tests:
      runs-on: ubuntu-latest
      container: kitrt/test:latest
      defaults:
        run:
          working-directory: ${{ github.workspace }}
      environment: coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        OMP_NUM_THREADS: 1
        OMP_DYNAMIC: FALSE
        OPENBLAS_NUM_THREADS: 1
        MKL_NUM_THREADS: 1

      steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build code
        run: |
          mkdir build && cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=ON -DBUILD_ML=OFF -DBUILD_CODE_COV=ON ..
          ninja

      - name: Run unit tests
        run: |
          cd build
          ./unit_tests 

      - name: Code coverage
        run: |
          cpp-coveralls -r . -b "build/" -i "src/" -i "include/" --exclude "ext/" --gcov-options "\-lp" --verbose
